"""add_performance_indexes

Revision ID: a08431b462b4
Revises: b37860466cab
Create Date: 2025-11-20 17:18:21.215880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08431b462b4'
down_revision: Union[str, Sequence[str], None] = 'b37860466cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_category_name_created', 'categories', ['name', 'created_at'], unique=False)
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index('idx_product_category_price', 'products', ['category_id', 'price'], unique=False)
    op.create_index('idx_product_category_status', 'products', ['category_id', 'status'], unique=False)
    op.create_index('idx_product_price_status', 'products', ['price', 'status'], unique=False)
    op.create_index('idx_product_seller_status', 'products', ['seller_id', 'status'], unique=False)
    op.create_index('idx_product_status_created', 'products', ['status', 'created_at'], unique=False)
    op.create_index('idx_product_status_created_desc', 'products', ['status', 'created_at'], unique=False)
    op.create_index('idx_product_title_status', 'products', ['title', 'status'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index('idx_user_email_created', 'users', ['email', 'created_at'], unique=False)
    op.create_index('idx_user_username_created', 'users', ['username', 'created_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('idx_user_username_created', table_name='users')
    op.drop_index('idx_user_email_created', table_name='users')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index('idx_product_title_status', table_name='products')
    op.drop_index('idx_product_status_created_desc', table_name='products')
    op.drop_index('idx_product_status_created', table_name='products')
    op.drop_index('idx_product_seller_status', table_name='products')
    op.drop_index('idx_product_price_status', table_name='products')
    op.drop_index('idx_product_category_status', table_name='products')
    op.drop_index('idx_product_category_price', table_name='products')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_index('idx_category_name_created', table_name='categories')
    # ### end Alembic commands ###
